_file_name: Distribution_Of_Problem_Grades.yaml
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: b31154e0-afed-4445-b90d-a501d555784e
description: 'This chart shows the number of students who scored within a certain
  percentage of points for this problem. For problems that are pass/fail it will only
  show the lowest and highest percentage ranges. '
params:
  adhoc_filters: []
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  dashboards:
  - 23
  datasource: 15__table
  extra_form_data: {}
  granularity_sqla: emission_time
  groupby:
  - grade_bucket
  metrics:
  - count
  order_bars: true
  order_desc: true
  rich_tooltip: true
  row_limit: 10000
  show_legend: false
  slice_id: 345
  time_range: 'DATEADD(DATETIME("now"), -1, month) : DATEADD(DATETIME("now"), 1, day)'
  viz_type: dist_bar
  x_axis_label: Percentage Grade
  x_ticks_layout: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_label: Students
query_context: '{"datasource":{"id":15,"type":"table"},"force":false,"queries":[{"time_range":"DATEADD(DATETIME(\"now\"),
  -1, month) : DATEADD(DATETIME(\"now\"), 1, day)","granularity":"emission_time","filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["grade_bucket"],"metrics":["count"],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"15__table","viz_type":"dist_bar","slice_id":345,"granularity_sqla":"emission_time","time_range":"DATEADD(DATETIME(\"now\"),
  -1, month) : DATEADD(DATETIME(\"now\"), 1, day)","metrics":["count"],"adhoc_filters":[],"groupby":["grade_bucket"],"columns":[],"row_limit":10000,"order_desc":true,"color_scheme":"supersetColors","show_legend":false,"rich_tooltip":true,"order_bars":true,"y_axis_format":"SMART_NUMBER","y_axis_label":"Students","y_axis_bounds":[null,null],"x_axis_label":"Percentage
  Grade","bottom_margin":"auto","x_ticks_layout":"auto","extra_form_data":{},"dashboards":[23],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
slice_name: Distribution Of Problem Grades
uuid: 4f7e3606-f5de-4643-97c0-bbb6340a3df2
version: 1.0.0
viz_type: dist_bar
