_file_name: Distinct_forum_users.yaml
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 39d1e786-c0c8-4c56-81c8-56fb0df88001
description: null
params:
  adhoc_filters: []
  dashboards:
  - 61
  datasource: 57__table
  extra_form_data: {}
  granularity_sqla: emission_time
  header_font_size: 0.4
  metric:
    aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: actor_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 445
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: String
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    datasourceWarning: false
    expressionType: SIMPLE
    hasCustomLabel: false
    label: COUNT_DISTINCT(actor_id)
    optionName: metric_5y4uvwa13v4_f12i3twecs6
    sqlExpression: null
  subheader_font_size: 0.15
  time_format: smart_date
  time_range: No filter
  viz_type: big_number_total
  y_axis_format: SMART_NUMBER
query_context: '{"datasource": {"id": 57, "type": "table"}, "force": false, "queries":
  [{"time_range": "No filter", "filters": [], "extras": {"having": "", "where": ""},
  "applied_time_extras": {}, "columns": [], "metrics": [{"expressionType": "SIMPLE",
  "column": {"advanced_data_type": null, "certification_details": null, "certified_by":
  null, "column_name": "actor_id", "description": null, "expression": null, "filterable":
  true, "groupby": true, "id": 445, "is_certified": false, "is_dttm": false, "python_date_format":
  null, "type": "String", "type_generic": 1, "verbose_name": null, "warning_markdown":
  null}, "aggregate": "COUNT_DISTINCT", "sqlExpression": null, "datasourceWarning":
  false, "hasCustomLabel": false, "label": "COUNT_DISTINCT(actor_id)", "optionName":
  "metric_5y4uvwa13v4_f12i3twecs6"}], "annotation_layers": [], "series_limit": 0,
  "order_desc": true, "url_params": {}, "custom_params": {}, "custom_form_data": {}}],
  "form_data": {"datasource": "57__table", "viz_type": "big_number_total", "granularity_sqla":
  "emission_time", "time_range": "No filter", "metric": {"expressionType": "SIMPLE",
  "column": {"advanced_data_type": null, "certification_details": null, "certified_by":
  null, "column_name": "actor_id", "description": null, "expression": null, "filterable":
  true, "groupby": true, "id": 445, "is_certified": false, "is_dttm": false, "python_date_format":
  null, "type": "String", "type_generic": 1, "verbose_name": null, "warning_markdown":
  null}, "aggregate": "COUNT_DISTINCT", "sqlExpression": null, "datasourceWarning":
  false, "hasCustomLabel": false, "label": "COUNT_DISTINCT(actor_id)", "optionName":
  "metric_5y4uvwa13v4_f12i3twecs6"}, "adhoc_filters": [], "header_font_size": 0.4,
  "subheader_font_size": 0.15, "y_axis_format": "SMART_NUMBER", "time_format": "smart_date",
  "extra_form_data": {}, "dashboards": [61], "force": false, "result_format": "json",
  "result_type": "full"}, "result_format": "json", "result_type": "full"}'
slice_name: Distinct forum users
uuid: feb323ad-c819-49ca-a336-584bd9ff1a2e
version: 1.0.0
viz_type: big_number_total
