_file_name: Responses_Per_Problem.yaml
cache_timeout: null
certification_details: null
certified_by: null
dataset_uuid: 9362354c-1541-43c2-b769-da9818236298
description: The number of students who have responded to a question, and whether
  they have ever answered correctly. Students can answer some questions multiple times,
  but this chart counts each student only once per question.
params:
  adhoc_filters: []
  bar_stacked: true
  bottom_margin: auto
  color_scheme: supersetColors
  columns:
  - success
  dashboards:
  - 23
  datasource: 2__table
  extra_form_data: {}
  groupby:
  - problem_name
  metrics:
  - aggregate: COUNT_DISTINCT
    column:
      advanced_data_type: null
      certification_details: null
      certified_by: null
      column_name: actor_id
      description: null
      expression: null
      filterable: true
      groupby: true
      id: 301
      is_certified: false
      is_dttm: false
      python_date_format: null
      type: String
      type_generic: 1
      verbose_name: null
      warning_markdown: null
    expressionType: SIMPLE
    hasCustomLabel: true
    isNew: false
    label: Learners
    optionName: metric_g889221mh0r_lf203igqxgg
    sqlExpression: null
  order_bars: false
  order_desc: true
  rich_tooltip: true
  row_limit: 10000
  show_controls: false
  show_legend: false
  slice_id: 262
  time_range: 'DATEADD(DATETIME("now"), -1, month) : DATEADD(DATETIME("now"), 1, day)'
  viz_type: dist_bar
  x_axis_label: Question Title
  x_ticks_layout: auto
  y_axis_bounds:
  - null
  - null
  y_axis_format: SMART_NUMBER
  y_axis_label: Number Of Students
query_context: '{"datasource":{"id":2,"type":"table"},"force":false,"queries":[{"time_range":"DATEADD(DATETIME(\"now\"),
  -1, month) : DATEADD(DATETIME(\"now\"), 1, day)","filters":[],"extras":{"having":"","where":""},"applied_time_extras":{},"columns":["problem_name","success"],"metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"actor_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":301,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"String","type_generic":1,"verbose_name":null,"warning_markdown":null},"expressionType":"SIMPLE","hasCustomLabel":true,"isNew":false,"label":"Learners","optionName":"metric_g889221mh0r_lf203igqxgg","sqlExpression":null}],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"2__table","viz_type":"dist_bar","slice_id":262,"time_range":"DATEADD(DATETIME(\"now\"),
  -1, month) : DATEADD(DATETIME(\"now\"), 1, day)","metrics":[{"aggregate":"COUNT_DISTINCT","column":{"advanced_data_type":null,"certification_details":null,"certified_by":null,"column_name":"actor_id","description":null,"expression":null,"filterable":true,"groupby":true,"id":301,"is_certified":false,"is_dttm":false,"python_date_format":null,"type":"String","type_generic":1,"verbose_name":null,"warning_markdown":null},"expressionType":"SIMPLE","hasCustomLabel":true,"isNew":false,"label":"Learners","optionName":"metric_g889221mh0r_lf203igqxgg","sqlExpression":null}],"adhoc_filters":[],"groupby":["problem_name"],"columns":["success"],"row_limit":10000,"order_desc":true,"color_scheme":"supersetColors","show_legend":false,"rich_tooltip":true,"bar_stacked":true,"order_bars":false,"y_axis_format":"SMART_NUMBER","y_axis_label":"Number
  Of Students","show_controls":false,"y_axis_bounds":[null,null],"x_axis_label":"Question
  Title","bottom_margin":"auto","x_ticks_layout":"auto","extra_form_data":{},"dashboards":[23],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
slice_name: Responses Per Problem
uuid: 3dc6a642-a71d-4c8c-ab98-14f54852b40f
version: 1.0.0
viz_type: dist_bar
